/**
 * WORK CALENDAR - the single definition of a working day. PROTOTYPE ONLY.
 *
 * A working day is Monday to Friday AND not an observed U.S. federal holiday.
 * The backward-scheduling engine (scheduleModel.ts) and the Gantt's
 * non-working-day shading (DemoGantt.tsx) both read this file, so the days the
 * engine refuses to count are exactly the days the timeline shades. There is
 * no second calendar and no holiday rule anywhere else.
 *
 * Dates are ISO `YYYY-MM-DD` strings at the boundaries and UTC `Date`s inside,
 * matching the rest of the model; nothing here reads the local clock.
 */

const MS = 86400000;

export function iso(d: Date): string {
  return d.toISOString().slice(0, 10);
}
export function parse(s: string): Date {
  return new Date(s + 'T00:00:00Z');
}
const addDays = (d: Date, n: number) => new Date(d.getTime() + n * MS);

/* ---------------------------------------------------------------- holidays */

export type Holiday = {
  /** The observed, non-working date (ISO). */
  date: string;
  name: string;
  /** The statutory date when observance moved it off a weekend (ISO).
      Absent when the holiday is observed on its own day. */
  actualDate?: string;
};

/** Human label: the name, plus "(observed)" when the date was shifted. */
export const holidayLabel = (h: Holiday) => (h.actualDate ? `${h.name} (observed)` : h.name);

/** Nth <weekday> of a month (weekday 0 = Sunday, month 0 = January). */
function nthWeekday(year: number, month: number, weekday: number, n: number): Date {
  const first = new Date(Date.UTC(year, month, 1));
  const offset = (weekday - first.getUTCDay() + 7) % 7;
  return new Date(Date.UTC(year, month, 1 + offset + (n - 1) * 7));
}
/** Last <weekday> of a month. */
function lastWeekday(year: number, month: number, weekday: number): Date {
  const last = new Date(Date.UTC(year, month + 1, 0));
  const offset = (last.getUTCDay() - weekday + 7) % 7;
  return addDays(last, -offset);
}
/** Federal observance: a Saturday holiday is taken on the Friday before, a
    Sunday holiday on the Monday after (5 U.S.C. 6103(b)). */
function observed(actual: Date): Date {
  const g = actual.getUTCDay();
  return g === 6 ? addDays(actual, -1) : g === 0 ? addDays(actual, 1) : actual;
}

/**
 * The eleven U.S. federal holidays for any year, generated by rule rather than
 * listed, so a schedule that runs into another year is covered without a
 * second table. Fixed-date holidays carry their observance shift; the rest
 * are defined as a weekday and cannot land on a weekend.
 */
function federalHolidays(year: number): Holiday[] {
  const fixed = (month: number, day: number, name: string): Holiday => {
    const actual = new Date(Date.UTC(year, month, day));
    const obs = observed(actual);
    return obs.getTime() === actual.getTime()
      ? { date: iso(obs), name }
      : { date: iso(obs), name, actualDate: iso(actual) };
  };
  const floating = (d: Date, name: string): Holiday => ({ date: iso(d), name });
  return [
    fixed(0, 1, "New Year's Day"),
    floating(nthWeekday(year, 0, 1, 3), 'Martin Luther King Jr. Day'),
    floating(nthWeekday(year, 1, 1, 3), "Washington's Birthday"),
    floating(lastWeekday(year, 4, 1), 'Memorial Day'),
    fixed(5, 19, 'Juneteenth National Independence Day'),
    fixed(6, 4, 'Independence Day'),
    floating(nthWeekday(year, 8, 1, 1), 'Labor Day'),
    floating(nthWeekday(year, 9, 1, 2), 'Columbus Day'),
    fixed(10, 11, 'Veterans Day'),
    floating(nthWeekday(year, 10, 4, 4), 'Thanksgiving Day'),
    fixed(11, 25, 'Christmas Day'),
  ];
}

/**
 * Observed holidays keyed by ISO date, per calendar year. Built from the
 * neighbouring years too, because observance can cross a year boundary: a
 * Saturday 1 January is taken on Friday 31 December of the year before.
 */
const holidayIndex = new Map<number, Map<string, Holiday>>();
function holidaysObservedIn(year: number): Map<string, Holiday> {
  let m = holidayIndex.get(year);
  if (!m) {
    m = new Map();
    for (const y of [year - 1, year, year + 1])
      for (const h of federalHolidays(y))
        if (h.date.startsWith(`${year}-`)) m.set(h.date, h);
    holidayIndex.set(year, m);
  }
  return m;
}

/** Every observed holiday in a calendar year, in date order. */
export function holidaysInYear(year: number): Holiday[] {
  return [...holidaysObservedIn(year).values()].sort((a, b) => (a.date < b.date ? -1 : 1));
}

/* ------------------------------------------------------------ predicates */

export function isWeekend(d: Date): boolean {
  const g = d.getUTCDay();
  return g === 0 || g === 6;
}
/** The holiday observed on this date, if any. */
export function holidayOn(d: Date): Holiday | null {
  return holidaysObservedIn(d.getUTCFullYear()).get(iso(d)) ?? null;
}
export function isHoliday(d: Date): boolean {
  return holidayOn(d) !== null;
}
/** THE DEFINITION. Monday to Friday, and not an observed federal holiday. */
export function isWorkingDay(d: Date): boolean {
  return !isWeekend(d) && !isHoliday(d);
}

/* ---------------------------------------------------- working-day arithmetic */

/** Previous working day strictly before `d`. */
export function prevWorkday(d: Date): Date {
  let r = addDays(d, -1);
  while (!isWorkingDay(r)) r = addDays(r, -1);
  return r;
}
/** Next working day strictly after `d`. */
export function nextWorkday(d: Date): Date {
  let r = addDays(d, 1);
  while (!isWorkingDay(r)) r = addDays(r, 1);
  return r;
}
/** Step back `n` working days from `d` (n=0 returns d). */
export function subWorkdays(d: Date, n: number): Date {
  let r = new Date(d);
  for (let i = 0; i < n; i++) r = prevWorkday(r);
  return r;
}
/** Step forward `n` working days from `d` (n=0 returns d). */
export function addWorkdays(d: Date, n: number): Date {
  let r = new Date(d);
  for (let i = 0; i < n; i++) r = nextWorkday(r);
  return r;
}
/** Snap onto a working day, moving backwards if necessary. */
export function snapBack(d: Date): Date {
  let r = new Date(d);
  while (!isWorkingDay(r)) r = addDays(r, -1);
  return r;
}
/** Inclusive count of working days between two dates. */
export function workdaysBetween(a: Date, b: Date): number {
  let n = 0;
  for (let r = new Date(a); r <= b; r = addDays(r, 1)) if (isWorkingDay(r)) n++;
  return n;
}

/* ------------------------------------------------------- for the timeline */

/** A maximal run of consecutive non-working days: a weekend, a holiday, or a
    holiday joined to the weekend beside it. */
export type NonWorkingRun = {
  /** First non-working day (inclusive). */
  start: Date;
  /** First working day after the run (exclusive). */
  end: Date;
  days: number;
  holidays: Holiday[];
};

/**
 * Every non-working run in [start, end). The Gantt positions these through the
 * same day scale as the bars, so a shaded column and the bar that stops beside
 * it can never disagree about where a day is.
 */
export function nonWorkingRuns(start: Date, end: Date): NonWorkingRun[] {
  const runs: NonWorkingRun[] = [];
  let open: NonWorkingRun | null = null;
  for (let d = new Date(start); d < end; d = addDays(d, 1)) {
    if (isWorkingDay(d)) {
      if (open) {
        open.end = new Date(d);
        runs.push(open);
        open = null;
      }
      continue;
    }
    if (!open) open = { start: new Date(d), end: addDays(d, 1), days: 0, holidays: [] };
    open.days++;
    const h = holidayOn(d);
    if (h) open.holidays.push(h);
  }
  if (open) {
    open.end = new Date(end);
    runs.push(open);
  }
  return runs;
}
